### PR TITLE
fix: add activatorEvent to resize events

### LINKED ISSUE #56: Add activatorEvent to resize events
### Discussed in https://github.com/samuelarbibe/dnd-timeline/discussions/55

<div type='discussions-op-text'>

<sup>Originally posted by **arwtyxouymz** September 24, 2024</sup>
Hi
This library is what I wanted! Thank you for your great work!

I have a question about pan strategy.
I want to scroll timeline vertically and horizontally by dragging without ctrl/meta key.
Is it possible to achieve it?

This is the current behavior.
Horizontal scroll is working, but vertical scroll is not.
It scales timeline range and select sidebar text.

https://github.com/user-attachments/assets/3e6c6c58-a2de-4cd2-b71c-39acca713810

This is my current `UsePanStrategy`. I referred to your default `useDragStrategy`.
I think other resource (probably `useItem` hook) event handler is triggered at the same time.
I appreciate your help and  I'm also happy to help contribute to this request if you'd like any assistance.
```ts
import { useLayoutEffect, useRef } from 'react';
import type { PanEndEvent, UsePanStrategy } from 'dnd-timeline';

export const useDragStrategy: UsePanStrategy = (timelineRef, onPanEnd) => {
  const lastDragPos = useRef<{ x: number; y: number } | null>(null);

  useLayoutEffect(() => {
    const element = timelineRef.current;
    if (!element) return;

    const pointerdownHandler = (event: MouseEvent) => {
      lastDragPos.current = { x: event.clientX, y: event.clientY };
    };

    const pointerupHandler = () => {
      lastDragPos.current = null;
    };

    const pointermoveHandler = (event: MouseEvent) => {
      if (!lastDragPos.current) return;

      const deltaX = event.clientX - lastDragPos.current.x;
      const deltaY = event.clientY - lastDragPos.current.y;

      lastDragPos.current = { x: event.clientX, y: event.clientY };

      const panEndEvent: PanEndEvent = {
        deltaX: -deltaX,
        deltaY: -deltaY,
      };

      onPanEnd(panEndEvent);
    };

    element.addEventListener('pointerup', pointerupHandler);
    element.addEventListener('pointerdown', pointerdownHandler);
    element.addEventListener('pointermove', pointermoveHandler);
    element.addEventListener('pointerleave', pointerupHandler);

    return () => {
      element.removeEventListener('pointerup', pointerupHandler);
      element.removeEventListener('pointerdown', pointerdownHandler);
      element.removeEventListener('pointermove', pointermoveHandler);
      element.removeEventListener('pointerleave', pointerupHandler);
    };
  }, [onPanEnd, timelineRef]);
};
```</div>

### PR DESCRIPTION
**Pull request by samuelarbibe**
Closes #56

### CODE REVIEW

File: packages/dnd-timeline/src/types/resize.ts [hunk 1]
```diff
@@ -11,6 +12,7 @@ export interface ResizeMoveEvent {
 export type ResizeEndEvent = ResizeMoveEvent;
 
 export interface ResizeStartEvent {
+	activatorEvent: Event;
```
Comment (arwtyxouymz) [inline packages/dnd-timeline/src/types/resize.ts:15]: Thank you for your great work! :+1:

Why not use `PointerEvent` here instead of just simple `Event`?
I think only `PointerEvent` will be passed to `ResizeXXXEvent`

Comment (samuelarbibe) [reply packages/dnd-timeline/src/types/resize.ts:15]: Hey!
Tried to match `dnd-kits`'s event types, where they use a generic `Event` to prevent limiting interaction to pointer.

For example, in `dnd-kit`, it is possible to control dragging using keyboard input.
To allow for future support of keyboard control, or other accessibility features, I preferred using `Event`.

Comment (arwtyxouymz) [reply packages/dnd-timeline/src/types/resize.ts:15]: I see. Understood! Thank you!
